version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: tinderapp_db
    environment:
      POSTGRES_DB: tinder_app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tinder-network

  tinderapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tinderapp_backend
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/tinder_app
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345
    networks:
      - tinder-network

volumes:
  pgdata:

networks:
  tinder-network:
